server:
  port: 8080
  servlet:
    context-path: /ecomerce
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
h2:
  console:
    enabled: true
    path: /h2-console


spring:
  security: #configurações de segurança com spring security
    user: admin
    password: admin
    name: admin
    roles: ADMIN
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/ecomercedb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: ecomerce
    password: ecomerce
    ddl-auto: update




